- name: Install MySQL on Vagrant
  hosts: all
  become: true
  vars_files:
    - vars.yaml
  tasks:
    - name: Copy the rpm file
      copy: 
        src: ./mysql80-community-release-el7-5.noarch.rpm
        dest: ~/
    - name: Install the repo
      yum: 
        name: /root/mysql80-community-release-el7-5.noarch.rpm
        state: present
    - name: Upgrade all packages
      yum:
        name: "*"
        state: latest
    - name: Install MySQL Server
      yum:
        name: 
          - mysql-server
          - vim
          - htop
        state: latest
    - name: Enable and start mysqld
      systemd:
        name: mysqld
        enabled: yes
        state: started

    - name: Detect the initial root password from /var/log/mysqld.log
      shell: grep -E 'A temporary password is generated for root@localhost' /var/log/mysqld.log | tail -1 | sed 's/^.*{{':'}} //'
      register: root_pass

    - name: Set passwordless login
      copy:
        dest: /root/.my.cnf
        content: |
          [client]
          password = "{{ root_pass.stdout }}"