- name: Install MySQL on Vagrant
  hosts: all
  become: true
  vars_files:
    - vars.yaml
  tasks:
    - name: Upgrade all packages
      yum:
        name: "*"
        state: latest
    - name: Add group
      group:
        name: mysql
        state: present
    - name: Add mysql user
      user:
        name: mysql
        system: True
        group: mysql
        shell: /bin/false
        state: present
    - name: mysql-server dir
      file:
        path: /usr/local/mysql-server
        state: directory
        group: mysql
        owner: mysql
    - name: untar MySQL binary
      become: true
      unarchive:
        src: ./mysql-8.0.28-linux-glibc2.12-i686.tar.xz
        dest: /usr/local/mysql-server
        # cd /usr/local
        # tar xvf /path/to/mysql-VERSION-OS.tar.xz

        
