- hosts: all
  tasks:
    - name: Install MySQL
        action: yum name={{ item }}
        with_items:
          - MySQL-python
          - mysql
          - mysql-server
    - name: Start the MySQL service
      action: service name=mysqld state=started
    