- hosts: all
  tasks:
    - name: Install MySQL
        action: yum name={{ item }}
        with_items:
          - MySQL-python
          - mysql
          - mysql-server
          - python39
          - python39-devel
          - python39-pip
          - gcc
        state: latest
    - name: Start the MySQL service
      action: service name=mysqld state=started
    