- name: Install MySQL on Vagrant
  hosts: all
  become: true
  vars_files:
    - vars.yaml
  tasks:
    - name: Copy the rpm file
      copy: 
        src: ./mysql80-community-release-el7-5.noarch.rpm
        dest: ~/
    - name: Upgrade all packages
      yum:
        name: "*"
        state: latest
    - name: Install the repo
      yum: 
        name: /root/mysql80-community-release-el7-5.noarch.rpm
        state: present
    - name: Install MySQL Server
      yum:
        name: mysql-server
        state: latest
    - name: Empty /var/lib/mysql directory
      shell: rm -rf /var/lib/mysql/*
    - name: Set default password
      copy:
        dest: /root/mysql-init
        content: "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('{{ mysql_root_password }}');"
    - name: Initialize MySQL
      shell: mysqld --user=root --init-file /root/mysql-init
    - name: Set passwordless login
      copy:
        dest: /root/.my.cnf
        content: |
          [client]
          password = {{ mysql_root_password }}
        mode: 600
    - name: Enable and start mysqld
      systemd:
        name: mysqld
        enabled: yes
        state: started